import type { ElectionData } from "./types";

// Seed data representing Nepal 2082 election results
// Used during development and as fallback when scraper is unavailable
export const SEED_DATA: ElectionData = {
  scrapedAt: new Date().toISOString(),
  national: {
    totalConstituencies: 165,
    resultsDeclared: 47,
    counting: 89,
    notStarted: 29,
    totalVotesCounted: 4820300,
    lastUpdated: new Date().toISOString(),
    partySeats: [
      {
        party: "Nepali Congress",
        partySlug: "nc",
        partyColor: "#1565C0",
        seats: 18,
        leading: 24,
        totalVotes: 1380000,
        votePercentage: 28.6,
      },
      {
        party: "CPN-UML",
        partySlug: "uml",
        partyColor: "#EF4444",
        seats: 15,
        leading: 22,
        totalVotes: 1240000,
        votePercentage: 25.7,
      },
      {
        party: "CPN (Maoist Centre)",
        partySlug: "mc",
        partyColor: "#B91C1C",
        seats: 7,
        leading: 11,
        totalVotes: 590000,
        votePercentage: 12.2,
      },
      {
        party: "Rastriya Swatantra Party",
        partySlug: "rastriya-swatantra",
        partyColor: "#10B981",
        seats: 4,
        leading: 9,
        totalVotes: 420000,
        votePercentage: 8.7,
      },
      {
        party: "Rastriya Prajatantra Party",
        partySlug: "rpp",
        partyColor: "#F59E0B",
        seats: 2,
        leading: 5,
        totalVotes: 310000,
        votePercentage: 6.4,
      },
      {
        party: "Others / Independent",
        partySlug: "others",
        partyColor: "#6B7280",
        seats: 1,
        leading: 18,
        totalVotes: 880300,
        votePercentage: 18.4,
      },
    ],
  },
  constituencies: [
    // ==================== JHAPA DISTRICT ====================
    {
      id: "jhapa-1",
      slug: "jhapa-1",
      name: "Jhapa-1",
      nameNepali: "झापा-१",
      district: "Jhapa",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 68420,
      totalVoters: 92000,
      countingStatus: "complete",
      countedPercentage: 100,
      lastUpdated: new Date().toISOString(),
      winner: undefined,
      candidates: [
        {
          id: "c-jhapa1-1",
          name: "Ram Kumar Subba",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 24180,
          percentage: 35.3,
          status: "elected",
          isWinner: true,
        },
        {
          id: "c-jhapa1-2",
          name: "Deepak Prasad Koirala",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 21650,
          percentage: 31.6,
          status: "lost",
        },
        {
          id: "c-jhapa1-3",
          name: "Sushila Karki",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 14320,
          percentage: 20.9,
          status: "lost",
        },
        {
          id: "c-jhapa1-4",
          name: "Kiran Rai",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 8270,
          percentage: 12.1,
          status: "lost",
        },
      ],
    },
    {
      id: "jhapa-2",
      slug: "jhapa-2",
      name: "Jhapa-2",
      nameNepali: "झापा-२",
      district: "Jhapa",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 71340,
      totalVoters: 95000,
      countingStatus: "complete",
      countedPercentage: 100,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-jhapa2-1",
          name: "Bishnu Prasad Poudel",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 26140,
          percentage: 36.6,
          status: "elected",
          isWinner: true,
        },
        {
          id: "c-jhapa2-2",
          name: "Gita Devi Acharya",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 23890,
          percentage: 33.5,
          status: "lost",
        },
        {
          id: "c-jhapa2-3",
          name: "Hari Bahadur Tamang",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 12100,
          percentage: 17.0,
          status: "lost",
        },
        {
          id: "c-jhapa2-4",
          name: "Sunita Thapa",
          party: "Rastriya Prajatantra Party",
          partySlug: "rpp",
          partyColor: "#F59E0B",
          votes: 9210,
          percentage: 12.9,
          status: "lost",
        },
      ],
    },
    {
      id: "jhapa-3",
      slug: "jhapa-3",
      name: "Jhapa-3",
      nameNepali: "झापा-३",
      district: "Jhapa",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 65820,
      totalVoters: 89000,
      countingStatus: "counting",
      countedPercentage: 78,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-jhapa3-1",
          name: "Narayan Kaji Shrestha",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 21340,
          percentage: 32.4,
          status: "leading",
          isWinner: false,
        },
        {
          id: "c-jhapa3-2",
          name: "Pradeep Kumar Gyawali",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 20100,
          percentage: 30.5,
          status: "trailing",
        },
        {
          id: "c-jhapa3-3",
          name: "Arjun Narsingh KC",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 16880,
          percentage: 25.6,
          status: "trailing",
        },
        {
          id: "c-jhapa3-4",
          name: "Mohan Bahadur Basnet",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 7500,
          percentage: 11.4,
          status: "trailing",
        },
      ],
    },
    {
      id: "jhapa-4",
      slug: "jhapa-4",
      name: "Jhapa-4",
      nameNepali: "झापा-४",
      district: "Jhapa",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 59240,
      totalVoters: 87000,
      countingStatus: "counting",
      countedPercentage: 55,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-jhapa4-1",
          name: "Shankar Pokhrel",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 19800,
          percentage: 33.4,
          status: "leading",
        },
        {
          id: "c-jhapa4-2",
          name: "Bimala Poudel Rana",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 18200,
          percentage: 30.7,
          status: "trailing",
        },
        {
          id: "c-jhapa4-3",
          name: "Rekha Sharma",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 13440,
          percentage: 22.7,
          status: "trailing",
        },
        {
          id: "c-jhapa4-4",
          name: "Bhim Bahadur Gyawali",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 7800,
          percentage: 13.2,
          status: "trailing",
        },
      ],
    },
    // FEATURED: Jhapa-5
    {
      id: "jhapa-5",
      slug: "jhapa-5",
      name: "Jhapa-5",
      nameNepali: "झापा-५",
      district: "Jhapa",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 74820,
      totalVoters: 98000,
      countingStatus: "counting",
      countedPercentage: 82,
      lastUpdated: new Date().toISOString(),
      isFeatured: true,
      candidates: [
        {
          id: "c-jhapa5-1",
          name: "Prakash Man Singh",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 27340,
          percentage: 36.5,
          status: "leading",
          isWinner: false,
        },
        {
          id: "c-jhapa5-2",
          name: "Bhim Rawal",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 23190,
          percentage: 31.0,
          status: "trailing",
        },
        {
          id: "c-jhapa5-3",
          name: "Dina Nath Sharma",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 13480,
          percentage: 18.0,
          status: "trailing",
        },
        {
          id: "c-jhapa5-4",
          name: "Kamala Khanal",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 10810,
          percentage: 14.4,
          status: "trailing",
        },
      ],
    },
    // ==================== KATHMANDU ====================
    {
      id: "kathmandu-1",
      slug: "kathmandu-1",
      name: "Kathmandu-1",
      nameNepali: "काठमाडौं-१",
      district: "Kathmandu",
      province: "Bagmati Province",
      provinceNumber: 3,
      type: "FPTP",
      totalVotes: 93400,
      totalVoters: 125000,
      countingStatus: "complete",
      countedPercentage: 100,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-ktm1-1",
          name: "Ranju Darshana",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 31200,
          percentage: 33.4,
          status: "elected",
          isWinner: true,
        },
        {
          id: "c-ktm1-2",
          name: "Gagan Thapa",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 28900,
          percentage: 30.9,
          status: "lost",
        },
        {
          id: "c-ktm1-3",
          name: "Yogesh Bhattarai",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 22100,
          percentage: 23.7,
          status: "lost",
        },
        {
          id: "c-ktm1-4",
          name: "Pampha Bhusal",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 11200,
          percentage: 12.0,
          status: "lost",
        },
      ],
    },
    {
      id: "kathmandu-2",
      slug: "kathmandu-2",
      name: "Kathmandu-2",
      nameNepali: "काठमाडौं-२",
      district: "Kathmandu",
      province: "Bagmati Province",
      provinceNumber: 3,
      type: "FPTP",
      totalVotes: 88200,
      totalVoters: 119000,
      countingStatus: "counting",
      countedPercentage: 91,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-ktm2-1",
          name: "Krishna Gopal Shrestha",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 29800,
          percentage: 33.8,
          status: "leading",
        },
        {
          id: "c-ktm2-2",
          name: "Surya Thapa",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 28100,
          percentage: 31.9,
          status: "trailing",
        },
        {
          id: "c-ktm2-3",
          name: "Manish Jha",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 17600,
          percentage: 19.9,
          status: "trailing",
        },
        {
          id: "c-ktm2-4",
          name: "Prem Suwal",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 12700,
          percentage: 14.4,
          status: "trailing",
        },
      ],
    },
    {
      id: "kathmandu-3",
      slug: "kathmandu-3",
      name: "Kathmandu-3",
      nameNepali: "काठमाडौं-३",
      district: "Kathmandu",
      province: "Bagmati Province",
      provinceNumber: 3,
      type: "FPTP",
      totalVotes: 0,
      totalVoters: 108000,
      countingStatus: "not-started",
      countedPercentage: 0,
      lastUpdated: new Date().toISOString(),
      candidates: [],
    },
    // ==================== POKHARA / KASKI ====================
    {
      id: "kaski-1",
      slug: "kaski-1",
      name: "Kaski-1",
      nameNepali: "कास्की-१",
      district: "Kaski",
      province: "Gandaki Province",
      provinceNumber: 4,
      type: "FPTP",
      totalVotes: 72100,
      totalVoters: 97000,
      countingStatus: "complete",
      countedPercentage: 100,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-kaski1-1",
          name: "Prithvi Subba Gurung",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 25600,
          percentage: 35.5,
          status: "elected",
          isWinner: true,
        },
        {
          id: "c-kaski1-2",
          name: "Siddha Raj Pathak",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 22900,
          percentage: 31.8,
          status: "lost",
        },
        {
          id: "c-kaski1-3",
          name: "Rekha Thapa",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 16100,
          percentage: 22.3,
          status: "lost",
        },
        {
          id: "c-kaski1-4",
          name: "Dil Kumar Acharya",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 7500,
          percentage: 10.4,
          status: "lost",
        },
      ],
    },
    // ==================== DHANKUTA ====================
    {
      id: "dhankuta-1",
      slug: "dhankuta-1",
      name: "Dhankuta-1",
      nameNepali: "धनकुटा-१",
      district: "Dhankuta",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 48300,
      totalVoters: 65000,
      countingStatus: "counting",
      countedPercentage: 63,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-dhankuta1-1",
          name: "Lal Babu Pandit",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 18200,
          percentage: 37.7,
          status: "leading",
        },
        {
          id: "c-dhankuta1-2",
          name: "Sushanta Mainali",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 16800,
          percentage: 34.8,
          status: "trailing",
        },
        {
          id: "c-dhankuta1-3",
          name: "Binda Pandey",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 13300,
          percentage: 27.5,
          status: "trailing",
        },
      ],
    },
    // ==================== CHITWAN ====================
    {
      id: "chitwan-1",
      slug: "chitwan-1",
      name: "Chitwan-1",
      nameNepali: "चितवन-१",
      district: "Chitwan",
      province: "Bagmati Province",
      provinceNumber: 3,
      type: "FPTP",
      totalVotes: 86700,
      totalVoters: 112000,
      countingStatus: "complete",
      countedPercentage: 100,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-chitwan1-1",
          name: "Renu Kumari Yadav",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 29400,
          percentage: 33.9,
          status: "elected",
          isWinner: true,
        },
        {
          id: "c-chitwan1-2",
          name: "Raghu Ji Pant",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 26100,
          percentage: 30.1,
          status: "lost",
        },
        {
          id: "c-chitwan1-3",
          name: "Bikas Lamsal",
          party: "Rastriya Swatantra Party",
          partySlug: "rastriya-swatantra",
          partyColor: "#10B981",
          votes: 18200,
          percentage: 21.0,
          status: "lost",
        },
        {
          id: "c-chitwan1-4",
          name: "Agni Sapkota",
          party: "CPN (Maoist Centre)",
          partySlug: "mc",
          partyColor: "#B91C1C",
          votes: 13000,
          percentage: 15.0,
          status: "lost",
        },
      ],
    },
    // ==================== MORANG ====================
    {
      id: "morang-1",
      slug: "morang-1",
      name: "Morang-1",
      nameNepali: "मोरङ-१",
      district: "Morang",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 0,
      totalVoters: 88000,
      countingStatus: "not-started",
      countedPercentage: 0,
      lastUpdated: new Date().toISOString(),
      candidates: [],
    },
    {
      id: "morang-2",
      slug: "morang-2",
      name: "Morang-2",
      nameNepali: "मोरङ-२",
      district: "Morang",
      province: "Koshi Province",
      provinceNumber: 1,
      type: "FPTP",
      totalVotes: 55400,
      totalVoters: 79000,
      countingStatus: "counting",
      countedPercentage: 70,
      lastUpdated: new Date().toISOString(),
      candidates: [
        {
          id: "c-morang2-1",
          name: "Subas Nembang",
          party: "CPN-UML",
          partySlug: "uml",
          partyColor: "#EF4444",
          votes: 20100,
          percentage: 36.3,
          status: "leading",
        },
        {
          id: "c-morang2-2",
          name: "Sita Gurung",
          party: "Nepali Congress",
          partySlug: "nc",
          partyColor: "#1565C0",
          votes: 18300,
          percentage: 33.0,
          status: "trailing",
        },
        {
          id: "c-morang2-3",
          name: "Hari Bhakta Kandel",
          party: "Rastriya Prajatantra Party",
          partySlug: "rpp",
          partyColor: "#F59E0B",
          votes: 17000,
          percentage: 30.7,
          status: "trailing",
        },
      ],
    },
  ],
};

// Ensure winners are set for 'complete' constituencies
for (const c of SEED_DATA.constituencies) {
  if (c.countingStatus === "complete" && c.candidates.length > 0) {
    const winner = c.candidates.find((ca) => ca.status === "elected");
    if (winner) c.winner = winner;
  }
}
